name: GraalVM Native Integration Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test with GraalVM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GraalVM Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libz-dev zlib1g-dev

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Native Integration Tests
        run: ./gradlew testNative

      - name: Build Docker image
        run: docker build -f ./src/main/docker/Dockerfile.native-micro -t virtuallyapp:0.0.1
