name: GraalVM Native Integration Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test with Java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Run Integration Tests
        run: ./gradlew build quarkusIntTest

      - name: Build Docker image
        run: docker build -f ./src/main/docker/Dockerfile.jvm -t virtuallyapp:0.0.1 .
